Repository prometium/IKBO-02-16-Coursework-JS, pull requests merged in 2019-12, with the labels that each got.

#1 Button component implemented
  src/base.css
  src/components/Button/Button.js
  src/components/Button/button.css
  src/components/Button/index.js
Labels: enhancement

#5 Update README.md
  README.md
Labels: enhancement

#4 Feature/rugged page
  package-lock.json
  package.json
  src/App.js
  src/components/Button/Button.js
  src/routes/Main/Main.js
  src/routes/RuggedPage/RuggedPage.js
  src/routes/RuggedPage/index.js
  src/routes/RuggedPage/rugged-page.css
Labels: enhancement

#9 Fix: overflow on main body
  docs/10.6573330679cad5ba963b.js
  docs/11.a6f3edd2b4207208ce68.js
  docs/12.d5085f1dc3ce514f189c.js
  docs/2.6219d81521048d433520.js
  docs/3.e58f549dd878faeb1b5b.js
  docs/4.4687185596783c5e4403.js
  docs/5.77410162031977a704d8.js
  docs/6.17a1ca2950ed51a24764.js
  docs/7.930de25ae44066e379f4.js
  docs/8.8b3ff835a92a51755f25.js
  docs/9.5f1bada180a53f09696b.js
  docs/index.html
  docs/main.89846f2602c8e4211b0a.js
  docs/vendors.71df04e95c73fa7cb6a8.js
  package-lock.json
  src/routes/AlwordPage/Alword-page.css
  src/routes/AlwordPage/AlwordPage.js
Labels: bug

#14 fixed and optimised docker deployment
  .dockerignore
  Dockerfile
  src/routes/VirachevPage/VirachevPage.js
Labels: bug, enhancement

#20 use VKLabel component and remove unused code
  src/components/VKLabel/VKLabel.js
  src/routes/RuggedPage/RuggedPage.js
Labels: enhancement
